// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sourcey.EntityFrameworkCore.Events.DbContexts;

#nullable disable

namespace EntityFrameworkCore.Migrations.EventStore
{
    [DbContext(typeof(EventStoreDbContext))]
    [Migration("20230901175457_AddEventStore")]
    partial class AddEventStore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sourcey.EntityFrameworkCore.Events.Entities.Event", b =>
                {
                    b.Property<long>("SequenceNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SequenceNo"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Causation")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Correlation")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("ScheduledPublication")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Version")
                        .HasColumnType("int");

                    b.HasKey("SequenceNo");

                    b.HasIndex("Actor");

                    b.HasIndex("Causation");

                    b.HasIndex("Correlation");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.HasIndex("StreamId");

                    b.HasIndex("Version");

                    b.ToTable("Event", "log");
                });
#pragma warning restore 612, 618
        }
    }
}
