name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      zion-dynamodb:
        image: "amazon/dynamodb-local:latest"
        ports:
          - "8000:8000"
    steps:
    - uses: actions/checkout@v2

    # Install .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    # Restore projects
    - name: Restore projects
      run: dotnet restore

    # Build projects
    - name: Build projects
      run: dotnet build --configuration Release --no-restore

    # Run test projects
    - name: Run test projects
      run: dotnet test Zion.sln --configuration Release --no-restore --no-build --verbosity normal --filter Category=Unit -- xunit.parallelizeAssembly=true
      env: 
        Zion_AWS__DynamoDB__Key: DUMMYIDEXAMPLE
        Zion_AWS__DynamoDB__Secret: DUMMYIDEXAMPLE
        Zion_AWS__DynamoDB__Region: eu-west
        Zion_AWS__DynamoDB__Host: http://localhost:8000